
package client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FileFaultException", targetNamespace = "http://www.example.com")
public class FileFaultException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FileFaultException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FileFaultException_Exception(String message, FileFaultException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FileFaultException_Exception(String message, FileFaultException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.FileFaultException
     */
    public FileFaultException getFaultInfo() {
        return faultInfo;
    }

}
